#!/bin/bash
cd /tmp/scriptver/ && rm -Rf .git
UVER=$(cat /tmp/scriptver/roman.ver)
echo "Server version:"
echo "$UVER"
read -r -p "Are you want to update? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        echo "Starting update..."
        ;;
    *)
        echo "Ok, update not completed."
        rm -Rf /tmp/scriptver/
        cd /home/$USER/bin/prepare && ./prepare
        ;;
esac
cd /tmp/scriptver/ && mv roman.ver version.txt && rm /home/$USER/bin/prepare/version/version.txt && cp version.txt /home/$USER/bin/prepare/version/
rm /home/$USER/bin/prepare/prepare
git clone -q https://github.com/RomanDesigner/script /home/$USER/bin/prepare
cd /home/$USER/bin/prepare/ && chmod +x prepare
read -r -p "Update succesfull. Start prepare command? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        cd /home/$USER/bin/prepare/ && ./prepare
        ;;
    *)
        echo "Ok."
        exit 0
        ;;
esac
