#!/bin/bash
echo "Server version:"
cd /home/$USER/prepare/tmp/ && cat roman.ver
read -r -p "Are you sure? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
       echo "Update started..."
        ;;
    *)
        echo "Update canceled."
        exit 0
        ;;
esac
echo "Update started..."
cd /home/$USER/prepare/tmp/ && cp roman.ver version.txt
cd /home/$USER/prepare/tmp/ && cp version.txt /home/$USER/bin/prepare/version/


cd /home/$USER/prepare/ && rm -Rf tmp
